//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int BooksID { get; set; }
        public System.DateTime DateOfSales { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
