//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ID { get; set; }
        public int BooksID { get; set; }
        public int QuantityBooks { get; set; }
        public System.DateTime DateSales { get; set; }
        public decimal PriceSales { get; set; }
        public string Picture { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
